POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Alessandro Chiarelli",
    "author": "alexcarchiar",
    "url": "alessandrochiarelli.com",
    "likes": 10
}
###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Lorenzo Callegari",
    "author": "lorcalhost",
    "url": "lorcalhost.com",
    "likes": 10
}
###
GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/