POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Alessandro Chiarelli",
    "author": "alexcarchiar",
    "url": "alessandrochiarelli.com",
    "likes": 10
}
###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Apple",
    "author": "Steve Jobs",
    "url": "apple.com",
    "likes": 100
}
###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "likes": 12,
  "url": "dijkstra.com"
}
###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXhjYXJjaGlhciIsImlkIjoiNjE1MWMzZmE5MmU4NmQxNTA1NTAyMjFjIiwiaWF0IjoxNjMyNzUxMDQ2fQ.n7Ekt8fMrooBdrcM3_nxBUng4isQBn6kuw3PireUkxw

{
    "title": "Alessandro Chiarelli",
    "author": "alexcarchiar",
    "url": "alessandrochiarelli.com",
    "likes": 10,
    "userId": "6151c3fa92e86d150550221c"
}
###
GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/
###
DELETE http://localhost:3001/api/blogs/614642944c2d68b8ac8dd311
###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "alexcarchiar", 
    "name": "Alessandro", 
    "password": "P4$$w0rd"
}
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "alexcarchiar", 
    "password": "P4$$w0rd"
}
###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXhjYXJjaGlhciIsImlkIjoiNjE1MWMzZmE5MmU4NmQxNTA1NTAyMjFjIiwiaWF0IjoxNjMyNzUxMDQ2fQ.n7Ekt8fMrooBdrcM3_nxBUng4isQBn6kuw3PireUkxw

{
    "title": "Alessandro Chiarelli",
    "author": "alexcarchiar",
    "url": "alessandrochiarelli.com",
    "likes": 10,
    "userId": "6151c3fa92e86d150550221c"
}